# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\liuya\Desktop\SR_work\miangui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1543, 642)
        Dialog.setMaximumSize(QtCore.QSize(1543, 642))
        Dialog.setBaseSize(QtCore.QSize(1543, 642))
        Dialog.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        Dialog.setAutoFillBackground(False)
        Dialog.setSizeGripEnabled(False)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(630, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(1130, 70, 401, 381))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setGeometry(QtCore.QRect(30, 40, 341, 221))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setObjectName("textBrowser")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(30, 270, 381, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label11 = QtWidgets.QLabel(self.groupBox_2)
        self.label11.setGeometry(QtCore.QRect(30, 310, 341, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setAutoFillBackground(False)
        self.label11.setStyleSheet("background-color: rgb(215, 227, 250);\n"
"color: rgb(255, 0, 0);")
        self.label11.setAlignment(QtCore.Qt.AlignCenter)
        self.label11.setWordWrap(False)
        self.label11.setObjectName("label11")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(1130, 460, 401, 171))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton1.setGeometry(QtCore.QRect(150, 50, 101, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton1.setFont(font)
        self.pushButton1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton1.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 0, 0);\n"
"background-color: rgb(85, 170, 0);\n"
"")
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton2.setGeometry(QtCore.QRect(270, 50, 101, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton2.setFont(font)
        self.pushButton2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 127);\n"
"selection-background-color: rgb(255, 0, 0);")
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton3.setGeometry(QtCore.QRect(30, 50, 101, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton3.setFont(font)
        self.pushButton3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton3.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 0, 0);\n"
"background-color: rgb(55, 111, 167);")
        self.pushButton3.setObjectName("pushButton3")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 331, 561))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label3 = QtWidgets.QLabel(self.groupBox)
        self.label3.setGeometry(QtCore.QRect(40, 140, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setAutoFillBackground(False)
        self.label3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setWordWrap(False)
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.groupBox)
        self.label4.setGeometry(QtCore.QRect(180, 140, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setAutoFillBackground(False)
        self.label4.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setWordWrap(False)
        self.label4.setObjectName("label4")
        self.label7 = QtWidgets.QLabel(self.groupBox)
        self.label7.setGeometry(QtCore.QRect(40, 340, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label7.setFont(font)
        self.label7.setAutoFillBackground(False)
        self.label7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label7.setAlignment(QtCore.Qt.AlignCenter)
        self.label7.setWordWrap(False)
        self.label7.setObjectName("label7")
        self.label2 = QtWidgets.QLabel(self.groupBox)
        self.label2.setGeometry(QtCore.QRect(180, 40, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setAutoFillBackground(False)
        self.label2.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setWordWrap(False)
        self.label2.setObjectName("label2")
        self.label10 = QtWidgets.QLabel(self.groupBox)
        self.label10.setGeometry(QtCore.QRect(180, 440, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label10.setFont(font)
        self.label10.setAutoFillBackground(False)
        self.label10.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label10.setAlignment(QtCore.Qt.AlignCenter)
        self.label10.setWordWrap(False)
        self.label10.setObjectName("label10")
        self.label5 = QtWidgets.QLabel(self.groupBox)
        self.label5.setGeometry(QtCore.QRect(40, 240, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setAutoFillBackground(False)
        self.label5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setWordWrap(False)
        self.label5.setObjectName("label5")
        self.label8 = QtWidgets.QLabel(self.groupBox)
        self.label8.setGeometry(QtCore.QRect(180, 340, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setAutoFillBackground(False)
        self.label8.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label8.setAlignment(QtCore.Qt.AlignCenter)
        self.label8.setWordWrap(False)
        self.label8.setObjectName("label8")
        self.label9 = QtWidgets.QLabel(self.groupBox)
        self.label9.setGeometry(QtCore.QRect(40, 440, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label9.setFont(font)
        self.label9.setAutoFillBackground(False)
        self.label9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label9.setAlignment(QtCore.Qt.AlignCenter)
        self.label9.setWordWrap(False)
        self.label9.setObjectName("label9")
        self.label1 = QtWidgets.QLabel(self.groupBox)
        self.label1.setGeometry(QtCore.QRect(40, 40, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setAutoFillBackground(False)
        self.label1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setObjectName("label1")
        self.label6 = QtWidgets.QLabel(self.groupBox)
        self.label6.setGeometry(QtCore.QRect(180, 240, 121, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setAutoFillBackground(False)
        self.label6.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setWordWrap(False)
        self.label6.setObjectName("label6")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(350, 70, 771, 561))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label5_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label5_4.setGeometry(QtCore.QRect(100, 330, 261, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label5_4.setFont(font)
        self.label5_4.setAutoFillBackground(False)
        self.label5_4.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label5_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label5_4.setWordWrap(False)
        self.label5_4.setObjectName("label5_4")
        self.label2_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label2_2.setGeometry(QtCore.QRect(180, 40, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label2_2.setFont(font)
        self.label2_2.setAutoFillBackground(False)
        self.label2_2.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_2.setWordWrap(False)
        self.label2_2.setObjectName("label2_2")
        self.label4_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_4.setGeometry(QtCore.QRect(180, 290, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label4_4.setFont(font)
        self.label4_4.setAutoFillBackground(False)
        self.label4_4.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label4_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_4.setWordWrap(False)
        self.label4_4.setObjectName("label4_4")
        self.label2_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label2_3.setGeometry(QtCore.QRect(540, 40, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label2_3.setFont(font)
        self.label2_3.setAutoFillBackground(False)
        self.label2_3.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_3.setWordWrap(False)
        self.label2_3.setObjectName("label2_3")
        self.label3_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label3_7.setGeometry(QtCore.QRect(540, 430, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label3_7.setFont(font)
        self.label3_7.setAutoFillBackground(False)
        self.label3_7.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label3_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_7.setWordWrap(False)
        self.label3_7.setObjectName("label3_7")
        self.label3_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label3_3.setGeometry(QtCore.QRect(540, 80, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label3_3.setFont(font)
        self.label3_3.setAutoFillBackground(False)
        self.label3_3.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_3.setWordWrap(False)
        self.label3_3.setObjectName("label3_3")
        self.label5_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label5_7.setGeometry(QtCore.QRect(100, 510, 261, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label5_7.setFont(font)
        self.label5_7.setAutoFillBackground(False)
        self.label5_7.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label5_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label5_7.setWordWrap(False)
        self.label5_7.setObjectName("label5_7")
        self.label4_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_7.setGeometry(QtCore.QRect(180, 470, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label4_7.setFont(font)
        self.label4_7.setAutoFillBackground(False)
        self.label4_7.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label4_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_7.setWordWrap(False)
        self.label4_7.setObjectName("label4_7")
        self.label5_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label5_6.setGeometry(QtCore.QRect(460, 510, 251, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label5_6.setFont(font)
        self.label5_6.setAutoFillBackground(False)
        self.label5_6.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label5_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label5_6.setWordWrap(False)
        self.label5_6.setObjectName("label5_6")
        self.label5_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label5_2.setGeometry(QtCore.QRect(100, 160, 261, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label5_2.setFont(font)
        self.label5_2.setAutoFillBackground(False)
        self.label5_2.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label5_2.setWordWrap(False)
        self.label5_2.setObjectName("label5_2")
        self.label1_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_4.setGeometry(QtCore.QRect(20, 210, 71, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_4.setFont(font)
        self.label1_4.setAutoFillBackground(False)
        self.label1_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_4.setWordWrap(False)
        self.label1_4.setObjectName("label1_4")
        self.label1_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_6.setGeometry(QtCore.QRect(20, 390, 71, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_6.setFont(font)
        self.label1_6.setAutoFillBackground(False)
        self.label1_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_6.setWordWrap(False)
        self.label1_6.setObjectName("label1_6")
        self.label4_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_3.setGeometry(QtCore.QRect(540, 120, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label4_3.setFont(font)
        self.label4_3.setAutoFillBackground(False)
        self.label4_3.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_3.setWordWrap(False)
        self.label4_3.setObjectName("label4_3")
        self.label1_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_2.setGeometry(QtCore.QRect(20, 40, 71, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_2.setFont(font)
        self.label1_2.setAutoFillBackground(False)
        self.label1_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_2.setWordWrap(False)
        self.label1_2.setObjectName("label1_2")
        self.label3_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label3_6.setGeometry(QtCore.QRect(180, 430, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label3_6.setFont(font)
        self.label3_6.setAutoFillBackground(False)
        self.label3_6.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_6.setWordWrap(False)
        self.label3_6.setObjectName("label3_6")
        self.label2_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label2_6.setGeometry(QtCore.QRect(540, 390, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label2_6.setFont(font)
        self.label2_6.setAutoFillBackground(False)
        self.label2_6.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_6.setWordWrap(False)
        self.label2_6.setObjectName("label2_6")
        self.label2_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label2_7.setGeometry(QtCore.QRect(180, 390, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label2_7.setFont(font)
        self.label2_7.setAutoFillBackground(False)
        self.label2_7.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label2_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_7.setWordWrap(False)
        self.label2_7.setObjectName("label2_7")
        self.label1_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_7.setGeometry(QtCore.QRect(380, 390, 71, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_7.setFont(font)
        self.label1_7.setAutoFillBackground(False)
        self.label1_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_7.setWordWrap(False)
        self.label1_7.setObjectName("label1_7")
        self.label1_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_3.setGeometry(QtCore.QRect(380, 40, 71, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_3.setFont(font)
        self.label1_3.setAutoFillBackground(False)
        self.label1_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_3.setWordWrap(False)
        self.label1_3.setObjectName("label1_3")
        self.label5_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label5_3.setGeometry(QtCore.QRect(460, 160, 261, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label5_3.setFont(font)
        self.label5_3.setAutoFillBackground(False)
        self.label5_3.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label5_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label5_3.setWordWrap(False)
        self.label5_3.setObjectName("label5_3")
        self.label3_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label3_4.setGeometry(QtCore.QRect(180, 250, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label3_4.setFont(font)
        self.label3_4.setAutoFillBackground(False)
        self.label3_4.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_4.setWordWrap(False)
        self.label3_4.setObjectName("label3_4")
        self.label2_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label2_4.setGeometry(QtCore.QRect(180, 210, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label2_4.setFont(font)
        self.label2_4.setAutoFillBackground(False)
        self.label2_4.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_4.setWordWrap(False)
        self.label2_4.setObjectName("label2_4")
        self.label4_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_6.setGeometry(QtCore.QRect(540, 470, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label4_6.setFont(font)
        self.label4_6.setAutoFillBackground(False)
        self.label4_6.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label4_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_6.setWordWrap(False)
        self.label4_6.setObjectName("label4_6")
        self.label3_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label3_2.setGeometry(QtCore.QRect(180, 80, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label3_2.setFont(font)
        self.label3_2.setAutoFillBackground(False)
        self.label3_2.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_2.setWordWrap(False)
        self.label3_2.setObjectName("label3_2")
        self.label4_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_2.setGeometry(QtCore.QRect(180, 120, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label4_2.setFont(font)
        self.label4_2.setAutoFillBackground(False)
        self.label4_2.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_2.setWordWrap(False)
        self.label4_2.setObjectName("label4_2")
        self.label1_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_8.setGeometry(QtCore.QRect(100, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_8.setFont(font)
        self.label1_8.setAutoFillBackground(False)
        self.label1_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_8.setWordWrap(False)
        self.label1_8.setObjectName("label1_8")
        self.label1_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_9.setGeometry(QtCore.QRect(100, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_9.setFont(font)
        self.label1_9.setAutoFillBackground(False)
        self.label1_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_9.setWordWrap(False)
        self.label1_9.setObjectName("label1_9")
        self.label1_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_10.setGeometry(QtCore.QRect(100, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_10.setFont(font)
        self.label1_10.setAutoFillBackground(False)
        self.label1_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_10.setWordWrap(False)
        self.label1_10.setObjectName("label1_10")
        self.label1_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_11.setGeometry(QtCore.QRect(20, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_11.setFont(font)
        self.label1_11.setAutoFillBackground(False)
        self.label1_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_11.setWordWrap(False)
        self.label1_11.setObjectName("label1_11")
        self.label1_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_12.setGeometry(QtCore.QRect(460, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_12.setFont(font)
        self.label1_12.setAutoFillBackground(False)
        self.label1_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_12.setWordWrap(False)
        self.label1_12.setObjectName("label1_12")
        self.label1_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_13.setGeometry(QtCore.QRect(460, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_13.setFont(font)
        self.label1_13.setAutoFillBackground(False)
        self.label1_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_13.setWordWrap(False)
        self.label1_13.setObjectName("label1_13")
        self.label1_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_14.setGeometry(QtCore.QRect(460, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_14.setFont(font)
        self.label1_14.setAutoFillBackground(False)
        self.label1_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_14.setWordWrap(False)
        self.label1_14.setObjectName("label1_14")
        self.label1_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_15.setGeometry(QtCore.QRect(380, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_15.setFont(font)
        self.label1_15.setAutoFillBackground(False)
        self.label1_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_15.setWordWrap(False)
        self.label1_15.setObjectName("label1_15")
        self.label1_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_16.setGeometry(QtCore.QRect(100, 210, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_16.setFont(font)
        self.label1_16.setAutoFillBackground(False)
        self.label1_16.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_16.setWordWrap(False)
        self.label1_16.setObjectName("label1_16")
        self.label1_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_17.setGeometry(QtCore.QRect(100, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_17.setFont(font)
        self.label1_17.setAutoFillBackground(False)
        self.label1_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_17.setWordWrap(False)
        self.label1_17.setObjectName("label1_17")
        self.label1_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_18.setGeometry(QtCore.QRect(100, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_18.setFont(font)
        self.label1_18.setAutoFillBackground(False)
        self.label1_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_18.setWordWrap(False)
        self.label1_18.setObjectName("label1_18")
        self.label1_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_19.setGeometry(QtCore.QRect(20, 330, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_19.setFont(font)
        self.label1_19.setAutoFillBackground(False)
        self.label1_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_19.setWordWrap(False)
        self.label1_19.setObjectName("label1_19")
        self.label3_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label3_5.setGeometry(QtCore.QRect(540, 250, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label3_5.setFont(font)
        self.label3_5.setAutoFillBackground(False)
        self.label3_5.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_5.setWordWrap(False)
        self.label3_5.setObjectName("label3_5")
        self.label1_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_5.setGeometry(QtCore.QRect(380, 210, 71, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_5.setFont(font)
        self.label1_5.setAutoFillBackground(False)
        self.label1_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(135, 133, 131);")
        self.label1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_5.setWordWrap(False)
        self.label1_5.setObjectName("label1_5")
        self.label5_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label5_5.setGeometry(QtCore.QRect(460, 330, 261, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label5_5.setFont(font)
        self.label5_5.setAutoFillBackground(False)
        self.label5_5.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label5_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5_5.setWordWrap(False)
        self.label5_5.setObjectName("label5_5")
        self.label4_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_5.setGeometry(QtCore.QRect(540, 290, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label4_5.setFont(font)
        self.label4_5.setAutoFillBackground(False)
        self.label4_5.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label4_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_5.setWordWrap(False)
        self.label4_5.setObjectName("label4_5")
        self.label2_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label2_5.setGeometry(QtCore.QRect(540, 210, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label2_5.setFont(font)
        self.label2_5.setAutoFillBackground(False)
        self.label2_5.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(4, 4, 4);")
        self.label2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_5.setWordWrap(False)
        self.label2_5.setObjectName("label2_5")
        self.label1_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_20.setGeometry(QtCore.QRect(460, 210, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_20.setFont(font)
        self.label1_20.setAutoFillBackground(False)
        self.label1_20.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_20.setWordWrap(False)
        self.label1_20.setObjectName("label1_20")
        self.label1_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_21.setGeometry(QtCore.QRect(460, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_21.setFont(font)
        self.label1_21.setAutoFillBackground(False)
        self.label1_21.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_21.setWordWrap(False)
        self.label1_21.setObjectName("label1_21")
        self.label1_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_22.setGeometry(QtCore.QRect(460, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_22.setFont(font)
        self.label1_22.setAutoFillBackground(False)
        self.label1_22.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_22.setWordWrap(False)
        self.label1_22.setObjectName("label1_22")
        self.label1_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_23.setGeometry(QtCore.QRect(380, 330, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_23.setFont(font)
        self.label1_23.setAutoFillBackground(False)
        self.label1_23.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_23.setWordWrap(False)
        self.label1_23.setObjectName("label1_23")
        self.label1_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_24.setGeometry(QtCore.QRect(100, 390, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_24.setFont(font)
        self.label1_24.setAutoFillBackground(False)
        self.label1_24.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_24.setWordWrap(False)
        self.label1_24.setObjectName("label1_24")
        self.label1_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_25.setGeometry(QtCore.QRect(100, 430, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_25.setFont(font)
        self.label1_25.setAutoFillBackground(False)
        self.label1_25.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_25.setWordWrap(False)
        self.label1_25.setObjectName("label1_25")
        self.label1_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_26.setGeometry(QtCore.QRect(100, 470, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_26.setFont(font)
        self.label1_26.setAutoFillBackground(False)
        self.label1_26.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_26.setWordWrap(False)
        self.label1_26.setObjectName("label1_26")
        self.label1_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_27.setGeometry(QtCore.QRect(20, 510, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_27.setFont(font)
        self.label1_27.setAutoFillBackground(False)
        self.label1_27.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_27.setWordWrap(False)
        self.label1_27.setObjectName("label1_27")
        self.label1_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_28.setGeometry(QtCore.QRect(460, 390, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_28.setFont(font)
        self.label1_28.setAutoFillBackground(False)
        self.label1_28.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_28.setWordWrap(False)
        self.label1_28.setObjectName("label1_28")
        self.label1_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_29.setGeometry(QtCore.QRect(460, 430, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_29.setFont(font)
        self.label1_29.setAutoFillBackground(False)
        self.label1_29.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_29.setWordWrap(False)
        self.label1_29.setObjectName("label1_29")
        self.label1_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_30.setGeometry(QtCore.QRect(460, 470, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_30.setFont(font)
        self.label1_30.setAutoFillBackground(False)
        self.label1_30.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_30.setWordWrap(False)
        self.label1_30.setObjectName("label1_30")
        self.label1_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label1_31.setGeometry(QtCore.QRect(380, 510, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label1_31.setFont(font)
        self.label1_31.setAutoFillBackground(False)
        self.label1_31.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 185, 185);")
        self.label1_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_31.setWordWrap(False)
        self.label1_31.setObjectName("label1_31")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SR 硬件生产测试系统"))
        self.label.setText(_translate("Dialog", "SR 硬件生产测试平台"))
        self.groupBox_2.setTitle(_translate("Dialog", "当前状态与测试进度"))
        self.label11.setText(_translate("Dialog", "请连接扫描枪！"))
        self.groupBox_3.setTitle(_translate("Dialog", "选项"))
        self.pushButton1.setText(_translate("Dialog", "生成PDF\n"
"写入数据库\n"
"打印标签\n"
"打印日志"))
        self.pushButton2.setText(_translate("Dialog", "取消本次测试"))
        self.pushButton3.setText(_translate("Dialog", "开始测试"))
        self.groupBox.setTitle(_translate("Dialog", "硬件信息"))
        self.label3.setText(_translate("Dialog", "控制器版本"))
        self.label4.setText(_translate("Dialog", "None"))
        self.label7.setText(_translate("Dialog", "是否合格"))
        self.label2.setText(_translate("Dialog", "未连接"))
        self.label10.setText(_translate("Dialog", "None"))
        self.label5.setText(_translate("Dialog", "测试固件版本"))
        self.label8.setText(_translate("Dialog", "None"))
        self.label9.setText(_translate("Dialog", "功能固件版本"))
        self.label1.setText(_translate("Dialog", "扫码枪状态"))
        self.label6.setText(_translate("Dialog", "None"))
        self.groupBox_4.setTitle(_translate("Dialog", "外设检测情况"))
        self.label5_4.setText(_translate("Dialog", "Note:Null"))
        self.label2_2.setText(_translate("Dialog", "None"))
        self.label4_4.setText(_translate("Dialog", "None"))
        self.label2_3.setText(_translate("Dialog", "None"))
        self.label3_7.setText(_translate("Dialog", "None"))
        self.label3_3.setText(_translate("Dialog", "None"))
        self.label5_7.setText(_translate("Dialog", "Note:Null"))
        self.label4_7.setText(_translate("Dialog", "None"))
        self.label5_6.setText(_translate("Dialog", "Note:Null"))
        self.label5_2.setText(_translate("Dialog", "Note:Null"))
        self.label1_4.setText(_translate("Dialog", "UART"))
        self.label1_6.setText(_translate("Dialog", "其他1"))
        self.label4_3.setText(_translate("Dialog", "None"))
        self.label1_2.setText(_translate("Dialog", "IO"))
        self.label3_6.setText(_translate("Dialog", "None"))
        self.label2_6.setText(_translate("Dialog", "None"))
        self.label2_7.setText(_translate("Dialog", "None"))
        self.label1_7.setText(_translate("Dialog", "其他2"))
        self.label1_3.setText(_translate("Dialog", "CAN"))
        self.label5_3.setText(_translate("Dialog", "Note:Null"))
        self.label3_4.setText(_translate("Dialog", "None"))
        self.label2_4.setText(_translate("Dialog", "None"))
        self.label4_6.setText(_translate("Dialog", "None"))
        self.label3_2.setText(_translate("Dialog", "None"))
        self.label4_2.setText(_translate("Dialog", "None"))
        self.label1_8.setText(_translate("Dialog", "DI"))
        self.label1_9.setText(_translate("Dialog", "DOR"))
        self.label1_10.setText(_translate("Dialog", "DOM"))
        self.label1_11.setText(_translate("Dialog", "Note"))
        self.label1_12.setText(_translate("Dialog", "丢包率"))
        self.label1_13.setText(_translate("Dialog", "误码率"))
        self.label1_14.setText(_translate("Dialog", "延迟"))
        self.label1_15.setText(_translate("Dialog", "Note"))
        self.label1_16.setText(_translate("Dialog", "丢包率"))
        self.label1_17.setText(_translate("Dialog", "误码率"))
        self.label1_18.setText(_translate("Dialog", "延迟"))
        self.label1_19.setText(_translate("Dialog", "Note"))
        self.label3_5.setText(_translate("Dialog", "None"))
        self.label1_5.setText(_translate("Dialog", "SPI"))
        self.label5_5.setText(_translate("Dialog", "Note:Null"))
        self.label4_5.setText(_translate("Dialog", "None"))
        self.label2_5.setText(_translate("Dialog", "None"))
        self.label1_20.setText(_translate("Dialog", "丢包率"))
        self.label1_21.setText(_translate("Dialog", "误码率"))
        self.label1_22.setText(_translate("Dialog", "延迟"))
        self.label1_23.setText(_translate("Dialog", "Note"))
        self.label1_24.setText(_translate("Dialog", "Note"))
        self.label1_25.setText(_translate("Dialog", "Note"))
        self.label1_26.setText(_translate("Dialog", "Note"))
        self.label1_27.setText(_translate("Dialog", "Note"))
        self.label1_28.setText(_translate("Dialog", "Note"))
        self.label1_29.setText(_translate("Dialog", "Note"))
        self.label1_30.setText(_translate("Dialog", "Note"))
        self.label1_31.setText(_translate("Dialog", "Note"))

